### ISSUE TITLE
Create bag of letters

### ISSUE THREAD

**Issue by paulakaferreira** [paulakaferreira/scrabble#6]
As differed from ou dictionnary of letters, this variable will contain all the letters we need  to our game. 

This should be a global variable that will be modified by our piece random function. The function should erase its return values from our bag of letters.

p.s: Very easy task. We only need to create an array of type char that contains all the letters.

**Comment by lucaslrx** [comment]
Hey there !
I think that a letter must be a structure, because a letter has several characteristics (number of letters in the bag, number of points associated with said letter)

The structure might be like :

```
struct lettre
{
  char id_lettre;
  int point_lettre;
  int quantite_lettre;
};

```

id_lettre being the letter itselft ('A', 'B', C',).
Then, each letter would be store in an array standing for the bag of letter. I'm not sure how to define all that yet. It would be a good idea to define a constant standing for the total number of letters in the alphabet.

(still getting used to github, sorry if I accidentally close an issue !)
